databases:
  - name: my_database_development
    databaseName: my_database_development # Adjust this if you have different environments
    user: my_database_development_user
    plan: free

services:
  - type: web
    name: Mattermost-clone-Action-cable
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # Uncomment if on paid instance
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my_database_development
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
